-- 002_seed_families.sql — 10 closed-dictionary families (spec §3.1)
-- Source: mvp-ui-mock/app/data.js (FAMILIES array)

INSERT OR IGNORE INTO families(id, display_name, prompt_guide, created_at, updated_at) VALUES
  ('sdxl', 'SDXL',
   'SDXL base guide. Use natural language. Keep descriptions concise. Token weight syntax (keyword:1.2).',
   strftime('%s','now'), strftime('%s','now')),
  ('illustrious', 'Illustrious',
   'Illustrious XL. Booru-style tags work. Trigger words from LoRA take precedence over generic style cues.',
   strftime('%s','now'), strftime('%s','now')),
  ('pony', 'Pony',
   'Pony Diffusion. Score tags are required: score_9, score_8_up, score_7_up. Rating tag at the end.',
   strftime('%s','now'), strftime('%s','now')),
  ('flux', 'Flux',
   'Flux.1. Natural language strongly preferred. Avoid booru tags. No negative prompt needed in most cases.',
   strftime('%s','now'), strftime('%s','now')),
  ('sd15', 'SD 1.5',
   'Stable Diffusion 1.5. Short, comma-separated tags work best. CFG 7–12. Negative prompt is important.',
   strftime('%s','now'), strftime('%s','now')),
  ('sd21', 'SD 2.1',
   'Stable Diffusion 2.1. Similar to 1.5 but larger token space. Needs explicit quality tags.',
   strftime('%s','now'), strftime('%s','now')),
  ('cascade', 'Stable Cascade',
   'Stable Cascade. Natural language. Two-stage process; prompts at both stages merged. Highly coherent.',
   strftime('%s','now'), strftime('%s','now')),
  ('hunyuan', 'HunyuanDiT',
   'HunyuanDiT. Chinese and English prompts both work. Bilingual model with strong semantic understanding.',
   strftime('%s','now'), strftime('%s','now')),
  ('kolors', 'Kolors',
   'Kolors by Kuaishou. Chinese-English bilingual. Natural language, high fidelity faces.',
   strftime('%s','now'), strftime('%s','now')),
  ('auraflow', 'AuraFlow',
   'AuraFlow v0.3. Natural language, flow-based diffusion. Avoid overly long prompts; concise descriptions work best.',
   strftime('%s','now'), strftime('%s','now'));
