// Seed data for sd-chisel prototype

const FAMILIES = [
  { id: 'sdxl', display_name: 'SDXL', prompt_guide: 'SDXL base guide. Use natural language. Keep descriptions concise. Token weight syntax (keyword:1.2).' },
  { id: 'illustrious', display_name: 'Illustrious', prompt_guide: 'Illustrious XL. Booru-style tags work. Trigger words from LoRA take precedence over generic style cues.' },
  { id: 'pony', display_name: 'Pony', prompt_guide: 'Pony Diffusion. Score tags are required: score_9, score_8_up, score_7_up. Rating tag at the end.' },
  { id: 'flux', display_name: 'Flux', prompt_guide: 'Flux.1. Natural language strongly preferred. Avoid booru tags. No negative prompt needed in most cases.' },
  { id: 'sd15', display_name: 'SD 1.5', prompt_guide: 'Stable Diffusion 1.5. Short, comma-separated tags work best. CFG 7–12. Negative prompt is important.' },
  { id: 'sd21', display_name: 'SD 2.1', prompt_guide: 'Stable Diffusion 2.1. Similar to 1.5 but larger token space. Needs explicit quality tags.' },
  { id: 'cascade', display_name: 'Stable Cascade', prompt_guide: 'Stable Cascade. Natural language. Two-stage process; prompts at both stages merged. Highly coherent.' },
  { id: 'hunyuan', display_name: 'HunyuanDiT', prompt_guide: 'HunyuanDiT. Chinese and English prompts both work. Bilingual model with strong semantic understanding.' },
  { id: 'kolors', display_name: 'Kolors', prompt_guide: 'Kolors by Kuaishou. Chinese-English bilingual. Natural language, high fidelity faces.' },
  { id: 'auraflow', display_name: 'AuraFlow', prompt_guide: 'AuraFlow v0.3. Natural language, flow-based diffusion. Avoid overly long prompts; concise descriptions work best.' },
];

const MODELS = [
  { name: 'juggernautXL_v10', display_name: 'Juggernaut XL v10', family_id: 'sdxl', author: 'RunDiffusion', version: '10.0', description: 'Photoreal SDXL finetune. Reduce CFG to 3.5–4.5.' },
  { name: 'realvisxl_v5', display_name: 'RealVis XL v5', family_id: 'sdxl', author: 'SG_161222', version: '5.0', description: 'Portrait-focused SDXL. Strong face detail.' },
  { name: 'illustriousXL_v01', display_name: 'Illustrious XL v0.1', family_id: 'illustrious', author: 'Onoma AI', version: '0.1', description: 'Anime base. Best with booru tagging.' },
  { name: 'ponyV6', display_name: 'Pony Diffusion V6 XL', family_id: 'pony', author: 'PurpleSmart', version: '6.0', description: 'Score tags are mandatory.' },
  { name: 'flux_dev', display_name: 'Flux.1 Dev', family_id: 'flux', author: 'Black Forest Labs', version: '1.0', description: 'Dev checkpoint. No negative prompt.' },
  { name: 'dreamshaperXL_v21', display_name: 'DreamShaper XL v2.1', family_id: 'sdxl', author: 'Lykon', version: '2.1', description: 'Versatile SDXL, good at stylized and semi-real.' },
  { name: 'zavychromaxl_b4', display_name: 'ZavyChromaXL b4', family_id: 'sdxl', author: 'ZavyChroma', version: 'b4', description: 'Vivid colors, high saturation, painterly look.' },
  { name: 'copaxTimelessxlSDXL1', display_name: 'CopaxTimeless XL', family_id: 'sdxl', author: 'Copax', version: '1.0', description: 'Timeless realism, good skin tones.' },
  { name: 'albedobaseXL_v21', display_name: 'AlbedoBase XL v2.1', family_id: 'sdxl', author: 'Albedo', version: '2.1', description: 'Semi-realistic. Good at stylized realism.' },
  { name: 'hassakuXL_v13', display_name: 'Hassaku XL v1.3', family_id: 'illustrious', author: 'Hassaku', version: '1.3', description: 'Anime SDXL. High fidelity characters.' },
  { name: 'animagineXL_v31', display_name: 'Animagine XL v3.1', family_id: 'illustrious', author: 'Cagliostro', version: '3.1', description: 'High-quality anime. Strong at character consistency.' },
  { name: 'kohakuXL_epsilon', display_name: 'Kohaku XL ε', family_id: 'illustrious', author: 'John6666', version: 'ε', description: 'Soft anime style, pastel tones.' },
  { name: 'noobaiXL_vPred', display_name: 'NoobAI XL vPred', family_id: 'illustrious', author: 'Noob', version: 'vPred', description: 'v-prediction anime base, very sharp.' },
  { name: 'epiCRealismXL_v7', display_name: 'epiCRealism XL v7', family_id: 'sdxl', author: 'epinikion', version: '7.0', description: 'Extreme photoreal. Best for portraits.' },
  { name: 'realisticVision_v60', display_name: 'Realistic Vision v6.0', family_id: 'sd15', author: 'SG_161222', version: '6.0', description: 'SD1.5 photoreal classic. CFG 7.' },
  { name: 'dreamshaper_v8', display_name: 'DreamShaper v8', family_id: 'sd15', author: 'Lykon', version: '8.0', description: 'Semi-realistic SD1.5. Very versatile.' },
  { name: 'revAnimated_v122', display_name: 'ReV Animated v1.22', family_id: 'sd15', author: 'Justin Maier', version: '1.22', description: 'Anime + real hybrid, SD1.5.' },
  { name: 'deliberate_v6', display_name: 'Deliberate v6', family_id: 'sd15', author: 'xKas', version: '6.0', description: 'Semi-realistic, controlled outputs.' },
  { name: 'absoluteReality_v181', display_name: 'AbsoluteReality v1.81', family_id: 'sd15', author: 'Lykon', version: '1.81', description: 'Hyperreal SD1.5. Very consistent.' },
  { name: 'toonyou_beta6', display_name: 'ToonYou beta6', family_id: 'sd15', author: 'tbc', version: 'b6', description: 'Cartoon / toon style, SD1.5.' },
  { name: 'ghostmix_v20', display_name: 'GhostMix v2.0', family_id: 'sd15', author: 'Ghost', version: '2.0', description: 'Semi-real anime hybrid. Smooth skin.' },
  { name: 'chilloutmix', display_name: 'ChillOutMix', family_id: 'sd15', author: 'TASUKU', version: '1.0', description: 'Korean aesthetic photoreal SD1.5.' },
  { name: 'anything_v5', display_name: 'Anything v5', family_id: 'sd15', author: 'Andite', version: '5.0', description: 'Classic anime SD1.5 base.' },
  { name: 'flux_schnell', display_name: 'Flux.1 Schnell', family_id: 'flux', author: 'Black Forest Labs', version: '1.0', description: 'Distilled fast inference. 4 steps.' },
  { name: 'flux_dev_fp8', display_name: 'Flux.1 Dev FP8', family_id: 'flux', author: 'Kijai', version: 'fp8', description: 'FP8 quantized dev. Lower VRAM.' },
  { name: 'fluxRealism_v1', display_name: 'Flux Realism v1', family_id: 'flux', author: 'XLabs', version: '1.0', description: 'Flux finetune for photoreal output.' },
  { name: 'fluxAnime_v1', display_name: 'Flux Anime v1', family_id: 'flux', author: 'Shakker Labs', version: '1.0', description: 'Anime-finetuned Flux model.' },
  { name: 'stableCascade_v10', display_name: 'Stable Cascade v1.0', family_id: 'cascade', author: 'Stability AI', version: '1.0', description: 'Stage B+C. Very high coherence.' },
  { name: 'stableCascade_cagliostro', display_name: 'Cascade — Cagliostro', family_id: 'cascade', author: 'Cagliostro', version: '1.0', description: 'Anime Cascade finetune.' },
  { name: 'hunyuanDiT_v11', display_name: 'HunyuanDiT v1.1', family_id: 'hunyuan', author: 'Tencent', version: '1.1', description: 'Full bilingual HunyuanDiT.' },
  { name: 'hunyuanDiT_v12', display_name: 'HunyuanDiT v1.2', family_id: 'hunyuan', author: 'Tencent', version: '1.2', description: 'Updated HunyuanDiT with better typography.' },
  { name: 'kolors_v10', display_name: 'Kolors v1.0', family_id: 'kolors', author: 'Kuaishou', version: '1.0', description: 'Original Kolors checkpoint.' },
  { name: 'kolors_virtual_try_on', display_name: 'Kolors Virtual Try-On', family_id: 'kolors', author: 'Kuaishou', version: '1.0', description: 'Kolors variant for clothing try-on.' },
  { name: 'auraflow_v03', display_name: 'AuraFlow v0.3', family_id: 'auraflow', author: 'fal.ai', version: '0.3', description: 'Latest AuraFlow checkpoint.' },
  { name: 'dreamshaperXL_lightning', display_name: 'DreamShaper XL Lightning', family_id: 'sdxl', author: 'Lykon', version: 'LCM', description: 'LCM distilled, 4–8 steps.' },
  { name: 'playgroundV25', display_name: 'Playground v2.5', family_id: 'sdxl', author: 'Playground AI', version: '2.5', description: 'High aesthetic quality. Best at 1024.' },
  { name: 'turbovisionXL_v43', display_name: 'TurboVision XL v4.3', family_id: 'sdxl', author: 'RunDiffusion', version: '4.3', description: 'Speed/quality tradeoff SDXL.' },
  { name: 'artificialguys_xl', display_name: 'ArtificialGuys XL', family_id: 'sdxl', author: 'ArtificialGuys', version: '1.0', description: 'Stylized painterly SDXL.' },
  { name: 'sd21_base', display_name: 'SD 2.1 Base', family_id: 'sd21', author: 'Stability AI', version: '2.1', description: 'Official SD 2.1 base checkpoint.' },
  { name: 'sd21_768', display_name: 'SD 2.1 768', family_id: 'sd21', author: 'Stability AI', version: '2.1-768', description: 'SD 2.1 high-res variant.' },
  { name: 'openjourney_v4', display_name: 'OpenJourney v4', family_id: 'sd15', author: 'PromptHero', version: '4.0', description: 'Midjourney-inspired style, SD1.5.' },
  { name: 'epicphotogasm_xplus', display_name: 'epiCPhotoGASM x+', family_id: 'sdxl', author: 'epinikion', version: 'x+', description: 'Extreme photoreal landscape and scene.' },
  { name: 'protovisionXL_v66', display_name: 'ProtoVision XL v6.6', family_id: 'sdxl', author: 'ProtoVision', version: '6.6', description: 'High-res artistic SDXL.' },
  { name: 'samaritan3dCartoon', display_name: 'Samaritan 3D Cartoon', family_id: 'sd15', author: 'Samaritan', version: '1.0', description: '3D cartoon style, SD1.5.' },
  { name: 'counterfeitXL_v25', display_name: 'Counterfeit XL v2.5', family_id: 'illustrious', author: 'Mcpower', version: '2.5', description: 'High detail anime, clean linework.' },
  { name: 'darkSushiMix_v225', display_name: 'DarkSushi Mix v2.25', family_id: 'sd15', author: 'Aitasai', version: '2.25', description: 'Dark aesthetic anime SD1.5.' },
  { name: 'flat2d_animerge', display_name: 'Flat-2D Animerge', family_id: 'sd15', author: 'Anashel', version: '1.0', description: 'Flat 2D illustration style.' },
  { name: 'waiANINSFW_v60', display_name: 'Wai-ANI v6.0', family_id: 'illustrious', author: 'wai-nsfw', version: '6.0', description: 'Illustrious anime finetune, versatile.' },
  { name: 'duchaitenAnimefull', display_name: 'DucHaiten AnimeFull', family_id: 'sd15', author: 'DucHaiten', version: '1.0', description: 'Full anime training SD1.5.' },
  { name: 'theAlly_v10', display_name: 'The Ally v1.0', family_id: 'sdxl', author: 'Ally', version: '1.0', description: 'Painterly SDXL, good at landscapes.' },
];

const LORAS = [
  { name: 'add_detail_xl', display_name: 'Add Detail XL', family_id: 'sdxl', tags: ['detail','texture'], trigger_words: ['detail enhancer','fine detail'], recommended_weight: 0.65, author: 'kohya', updated: '3d ago', description: 'Микроконтраст и деталь. Не комбинировать с другими detail-LoRA.' },
  { name: 'cinematic_lighting_v2', display_name: 'Cinematic Lighting v2', family_id: 'sdxl', tags: ['light','mood','style'], trigger_words: ['cinematic','rim light'], recommended_weight: 0.85, author: 'civitai', updated: '1w ago', description: 'Драматичный кинематографичный свет с rim-подсветкой.' },
  { name: 'character_redhead_v3', display_name: 'Character — Redhead v3', family_id: 'illustrious', tags: ['character','portrait'], trigger_words: ['red hair','long hair','green eyes'], recommended_weight: 1.00, author: 'you', updated: '4h ago', description: 'Персонаж: рыжие длинные волосы, зелёные глаза, веснушки.' },
  { name: 'anime_ink_style', display_name: 'Anime Ink Style', family_id: 'pony', tags: ['style','ink','linework'], trigger_words: ['ink','linework','sumi-e'], recommended_weight: 0.70, author: 'nerdy', updated: '2w ago', description: 'Чернильный анимешный стиль с акцентом на линию.' },
  { name: 'studio_portrait_v1', display_name: 'Studio Portrait v1', family_id: 'sdxl', tags: ['portrait','studio','light'], trigger_words: ['studio portrait','softbox'], recommended_weight: 0.80, author: 'you', updated: '1mo ago', description: 'Студийное softbox-освещение.' },
  { name: 'moody_atmosphere', display_name: 'Moody Atmosphere', family_id: 'flux', tags: ['mood','atmospheric'], trigger_words: ['moody','fog','overcast'], recommended_weight: 0.60, author: 'civitai', updated: '5d ago', description: 'Туманная, пасмурная атмосфера.' },
  { name: 'painterly_brush_v4', display_name: 'Painterly Brush v4', family_id: 'sdxl', tags: ['style','painterly'], trigger_words: ['oil paint','impasto'], recommended_weight: 0.75, author: 'you', updated: '2d ago', description: 'Масляная живопись, impasto-мазки.' },
  { name: 'crisp_line_art', display_name: 'Crisp Line Art', family_id: 'illustrious', tags: ['linework','ink'], trigger_words: ['clean lineart'], recommended_weight: 0.90, author: 'nerdy', updated: '3w ago', description: 'Чистая lineart без заливки.' },
  { name: 'dramatic_shadow', display_name: 'Dramatic Shadow', family_id: 'sdxl', tags: ['light','mood'], trigger_words: ['dramatic shadow','chiaroscuro'], recommended_weight: 0.80, author: 'civitai', updated: '6d ago', description: 'Чиароскуро, высокий контраст.' },
  { name: 'face_restoration_pony', display_name: 'Face Restoration Pony', family_id: 'pony', tags: ['detail','face'], trigger_words: ['face detail'], recommended_weight: 0.55, author: 'kohya', updated: '1mo ago', description: 'Детализация лица для Pony-моделей.' },
  { name: 'film_grain_warm', display_name: 'Film Grain — Warm', family_id: 'flux', tags: ['texture','film'], trigger_words: ['grain','kodachrome'], recommended_weight: 0.40, author: 'you', updated: '2d ago', description: 'Тёплое плёночное зерно.' },
  { name: 'character_elf_archer', display_name: 'Character — Elf Archer', family_id: 'illustrious', tags: ['character','fantasy'], trigger_words: ['elf','archer','pointed ears'], recommended_weight: 0.95, author: 'civitai', updated: '5d ago', description: 'Эльф-лучник, fantasy-сеттинг.' },
  { name: 'golden_hour', display_name: 'Golden Hour', family_id: 'sdxl', tags: ['light','mood'], trigger_words: ['golden hour','warm sunset'], recommended_weight: 0.75, author: 'civitai', updated: '1w ago', description: 'Тёплый закатный свет.' },
  { name: 'watercolor_wash_v2', display_name: 'Watercolor Wash v2', family_id: 'sdxl', tags: ['style','painterly'], trigger_words: ['watercolor','wet paint','wash'], recommended_weight: 0.80, author: 'you', updated: '3d ago', description: 'Акварельный стиль с размытыми краями.' },
  { name: 'neon_glow_fx', display_name: 'Neon Glow FX', family_id: 'sdxl', tags: ['light','style','fx'], trigger_words: ['neon','glow','cyberpunk lights'], recommended_weight: 0.70, author: 'civitai', updated: '4d ago', description: 'Неоновые огни и cyberpunk-эстетика.' },
  { name: 'character_knight_v2', display_name: 'Character — Knight v2', family_id: 'sdxl', tags: ['character','fantasy','armor'], trigger_words: ['knight','full plate armor','visor'], recommended_weight: 0.90, author: 'you', updated: '2w ago', description: 'Рыцарь в полном доспехе, медиевальный.' },
  { name: 'soft_bokeh', display_name: 'Soft Bokeh', family_id: 'sdxl', tags: ['detail','photo'], trigger_words: ['shallow dof','bokeh','lens blur'], recommended_weight: 0.55, author: 'kohya', updated: '5d ago', description: 'Мягкое боке, photographer look.' },
  { name: 'ink_splash_v3', display_name: 'Ink Splash v3', family_id: 'pony', tags: ['style','ink','fx'], trigger_words: ['ink splash','dynamic ink','splatter'], recommended_weight: 0.85, author: 'nerdy', updated: '1d ago', description: 'Динамичные брызги туши.' },
  { name: 'texture_stone_v1', display_name: 'Texture — Stone', family_id: 'sdxl', tags: ['texture','detail'], trigger_words: ['stone texture','rough surface','carved'], recommended_weight: 0.65, author: 'civitai', updated: '2w ago', description: 'Каменная текстура, подходит для окружения.' },
  { name: 'overcast_sky', display_name: 'Overcast Sky', family_id: 'flux', tags: ['mood','atmospheric','light'], trigger_words: ['overcast','grey sky','diffuse light'], recommended_weight: 0.50, author: 'you', updated: '4d ago', description: 'Пасмурное небо, рассеянный свет.' },
  { name: 'character_witch_v1', display_name: 'Character — Witch v1', family_id: 'illustrious', tags: ['character','fantasy'], trigger_words: ['witch','dark magic','pointed hat'], recommended_weight: 0.95, author: 'civitai', updated: '6d ago', description: 'Ведьма, dark fantasy образ.' },
  { name: 'micro_detail_face', display_name: 'Micro Detail — Face', family_id: 'sdxl', tags: ['detail','face','portrait'], trigger_words: ['pore detail','skin texture','sharp face'], recommended_weight: 0.60, author: 'kohya', updated: '1w ago', description: 'Микродетализация кожи и черт лица.' },
  { name: 'vintage_photo', display_name: 'Vintage Photo', family_id: 'sdxl', tags: ['style','film','texture'], trigger_words: ['vintage','aged photo','sepia','vignette'], recommended_weight: 0.65, author: 'you', updated: '3d ago', description: 'Эффект старой фотографии, выцветшие тона.' },
  { name: 'hard_surface_v2', display_name: 'Hard Surface v2', family_id: 'sdxl', tags: ['detail','texture','style'], trigger_words: ['hard surface','metal','mechanical detail'], recommended_weight: 0.75, author: 'civitai', updated: '5d ago', description: 'Металл и механика, hard-surface промышленный вид.' },
  { name: 'character_mage_v2', display_name: 'Character — Mage v2', family_id: 'illustrious', tags: ['character','fantasy'], trigger_words: ['mage','magic staff','spell casting'], recommended_weight: 0.90, author: 'you', updated: '1w ago', description: 'Маг с посохом, fantasy RPG.' },
  { name: 'dusk_light', display_name: 'Dusk Light', family_id: 'sdxl', tags: ['light','mood'], trigger_words: ['dusk','twilight','blue hour'], recommended_weight: 0.70, author: 'civitai', updated: '2d ago', description: 'Синий час, сумеречное освещение.' },
  { name: 'sketch_pencil_v2', display_name: 'Sketch Pencil v2', family_id: 'illustrious', tags: ['style','linework'], trigger_words: ['pencil sketch','rough sketch','graphite'], recommended_weight: 0.80, author: 'nerdy', updated: '4d ago', description: 'Карандашный скетч, ручная работа.' },
  { name: 'depth_fog', display_name: 'Depth Fog', family_id: 'sdxl', tags: ['mood','atmospheric','depth'], trigger_words: ['atmospheric fog','depth haze','distance fade'], recommended_weight: 0.55, author: 'you', updated: '1w ago', description: 'Глубинный туман, атмосферная перспектива.' },
  { name: 'character_rogue_v1', display_name: 'Character — Rogue v1', family_id: 'illustrious', tags: ['character','fantasy'], trigger_words: ['rogue','hood','dagger','shadow'], recommended_weight: 0.95, author: 'civitai', updated: '3d ago', description: 'Плут, стелс-образ с плащом.' },
  { name: 'cel_shading_v3', display_name: 'Cel Shading v3', family_id: 'pony', tags: ['style','anime'], trigger_words: ['cel shading','flat shading','toon'], recommended_weight: 0.85, author: 'nerdy', updated: '5d ago', description: 'Чёткое cel-shading для аниме стиля.' },
  { name: 'backlight_glow', display_name: 'Backlight Glow', family_id: 'sdxl', tags: ['light','style'], trigger_words: ['backlit','rim glow','contre-jour'], recommended_weight: 0.75, author: 'civitai', updated: '2w ago', description: 'Контровой свет, ореол вокруг силуэта.' },
  { name: 'fabric_detail_v1', display_name: 'Fabric Detail v1', family_id: 'sdxl', tags: ['detail','texture'], trigger_words: ['fabric','cloth detail','thread','weave'], recommended_weight: 0.60, author: 'kohya', updated: '6d ago', description: 'Детализация ткани и нитей.' },
  { name: 'character_dragon_rider', display_name: 'Character — Dragon Rider', family_id: 'illustrious', tags: ['character','fantasy'], trigger_words: ['dragon rider','saddle','scales'], recommended_weight: 0.90, author: 'you', updated: '1d ago', description: 'Всадник на драконе, эпичный образ.' },
  { name: 'hdr_contrast', display_name: 'HDR Contrast', family_id: 'sdxl', tags: ['detail','style'], trigger_words: ['hdr','high contrast','vivid colors'], recommended_weight: 0.65, author: 'civitai', updated: '4d ago', description: 'HDR-тональность, яркие насыщенные цвета.' },
  { name: 'halftone_print', display_name: 'Halftone Print', family_id: 'pony', tags: ['style','texture','fx'], trigger_words: ['halftone','dots','print','risograph'], recommended_weight: 0.70, author: 'nerdy', updated: '3d ago', description: 'Растровая печать, risograph-эстетика.' },
  { name: 'character_paladin', display_name: 'Character — Paladin', family_id: 'illustrious', tags: ['character','fantasy','armor'], trigger_words: ['paladin','holy warrior','glowing sigil'], recommended_weight: 0.95, author: 'civitai', updated: '5d ago', description: 'Паладин, светлый воин с сияющими символами.' },
  { name: 'lens_flare_v2', display_name: 'Lens Flare v2', family_id: 'sdxl', tags: ['light','fx'], trigger_words: ['lens flare','anamorphic flare','streak'], recommended_weight: 0.45, author: 'you', updated: '1w ago', description: 'Бликование линзы, кинематографический артефакт.' },
  { name: 'nature_lush_v1', display_name: 'Nature — Lush v1', family_id: 'sdxl', tags: ['mood','atmospheric'], trigger_words: ['lush vegetation','tropical','overgrown'], recommended_weight: 0.70, author: 'civitai', updated: '2w ago', description: 'Буйная растительность, тропическая среда.' },
  { name: 'character_necromancer', display_name: 'Character — Necromancer', family_id: 'pony', tags: ['character','fantasy'], trigger_words: ['necromancer','skull staff','dark robe'], recommended_weight: 0.90, author: 'nerdy', updated: '3d ago', description: 'Некромант, темная магия.' },
  { name: 'brutalist_architecture', display_name: 'Brutalist Architecture', family_id: 'sdxl', tags: ['style','texture'], trigger_words: ['brutalist','concrete','monolithic'], recommended_weight: 0.75, author: 'you', updated: '4d ago', description: 'Брутализм, голый бетон, монолитность.' },
  { name: 'character_samurai_v2', display_name: 'Character — Samurai v2', family_id: 'illustrious', tags: ['character','armor'], trigger_words: ['samurai','katana','kabuto','lamellar armor'], recommended_weight: 0.95, author: 'civitai', updated: '2d ago', description: 'Самурай в доспехе, феодальная Япония.' },
  { name: 'film_noir_v1', display_name: 'Film Noir v1', family_id: 'sdxl', tags: ['mood','style','light'], trigger_words: ['film noir','venetian blinds shadow','black and white'], recommended_weight: 0.80, author: 'you', updated: '5d ago', description: 'Нуар, полосатые тени, монохром.' },
  { name: 'glitch_art', display_name: 'Glitch Art', family_id: 'pony', tags: ['style','fx'], trigger_words: ['glitch','pixel corruption','vhs artifact'], recommended_weight: 0.60, author: 'nerdy', updated: '1w ago', description: 'VHS и цифровой глич.' },
  { name: 'character_bard', display_name: 'Character — Bard', family_id: 'illustrious', tags: ['character','fantasy'], trigger_words: ['bard','lute','colorful garb','feathered cap'], recommended_weight: 0.90, author: 'civitai', updated: '6d ago', description: 'Бард, разноцветный образ.' },
  { name: 'macro_lens_v1', display_name: 'Macro Lens v1', family_id: 'sdxl', tags: ['detail','photo'], trigger_words: ['macro','extreme closeup','shallow focus'], recommended_weight: 0.65, author: 'kohya', updated: '3d ago', description: 'Макросъёмка, экстремальный крупный план.' },
  { name: 'ukiyo_e_v2', display_name: 'Ukiyo-e v2', family_id: 'pony', tags: ['style','linework'], trigger_words: ['ukiyo-e','woodblock print','japanese art'], recommended_weight: 0.85, author: 'nerdy', updated: '4d ago', description: 'Японская гравюра укиё-э.' },
  { name: 'character_pirate', display_name: 'Character — Pirate', family_id: 'illustrious', tags: ['character'], trigger_words: ['pirate','tricorn hat','eye patch'], recommended_weight: 0.90, author: 'you', updated: '2d ago', description: 'Пират, морской разбойник.' },
  { name: 'ice_frost_v1', display_name: 'Ice & Frost v1', family_id: 'sdxl', tags: ['texture','fx','mood'], trigger_words: ['ice','frost','frozen','crystalline'], recommended_weight: 0.70, author: 'civitai', updated: '5d ago', description: 'Лёд и иней, хрустальные структуры.' },
  { name: 'character_alchemist', display_name: 'Character — Alchemist', family_id: 'illustrious', tags: ['character','fantasy'], trigger_words: ['alchemist','potion','flask','lab coat'], recommended_weight: 0.90, author: 'nerdy', updated: '1w ago', description: 'Алхимик с склянками и лабораторией.' },
  { name: 'painterly_impasto_v2', display_name: 'Painterly Impasto v2', family_id: 'sdxl', tags: ['style','painterly'], trigger_words: ['impasto','thick paint','palette knife','van gogh'], recommended_weight: 0.80, author: 'you', updated: '3d ago', description: 'Густые мазки, palette knife, Van Gogh-стиль.' },
];

// Seed projects and sessions
const PROJECTS = [
  { id: 'character-portraits', name: 'Character portraits' },
  { id: 'mood-tests', name: 'Mood tests' },
  { id: 'scrapyard', name: 'Scrapyard' },
];

const INITIAL_SESSIONS = [
  { id: 's-001', project_id: 'character-portraits', name: 'portrait · dusk v2',
    model_name: 'illustriousXL_v01', use_negative: true,
    pinned: ['character_redhead_v3'],
    source_image_path: 'https://images.unsplash.com/photo-1542827387-068e36bfc74c?w=900&q=80',
    vl_summary: 'Editorial portrait of a young woman with long red hair, illuminated by warm side light from camera-right. Shallow depth of field, slightly desaturated skin tones, neutral grey backdrop. Composition is tightly cropped from mid-chest up, with subject looking off-camera. Mood is pensive, cinematic.',
    messages: [
      { role: 'user', content: 'Хочу то же самое, но более драматично — чтобы свет был жёстче и тени глубже. И пусть будет чуть более пасмурно.' },
      { role: 'assistant', content: 'Понял — убираю мягкость студийного света, добавляю chiaroscuro и атмосферу.\n\nПодобрал:\n- `cinematic_lighting_v2` (0.85) — жёсткий rim и key\n- `dramatic_shadow` (0.7) — глубина в тенях\n- `moody_atmosphere` (0.5) — пасмурность, не пережать\n\nОставляю пинованный `character_redhead_v3` на 1.0. Готов собрать промпт?' },
    ],
    lastPrompt: {
      positive: 'editorial portrait, young woman, red hair long, green eyes, freckles, pensive expression, looking away, mid-chest crop, shallow depth of field, cinematic, rim light, dramatic shadow, chiaroscuro, moody, overcast, slightly desaturated, grey backdrop, 35mm',
      negative: 'soft studio light, softbox, flat lighting, saturated colors, cheerful, smiling, bright sunny, clean background, watermark, text',
      loras: [
        { name: 'character_redhead_v3', weight: 1.00, kind: 'pinned' },
        { name: 'cinematic_lighting_v2', weight: 0.85, kind: 'retrieved' },
        { name: 'dramatic_shadow', weight: 0.70, kind: 'retrieved' },
        { name: 'moody_atmosphere', weight: 0.50, kind: 'retrieved' },
      ],
      intents: [
        { kind: 'light', query: 'hard cinematic rim and key light' },
        { kind: 'mood', query: 'overcast moody atmosphere' },
        { kind: 'light', query: 'deep shadows chiaroscuro' },
      ],
      retrieved: [
        { intent: 0, loras: [['cinematic_lighting_v2', 0.91], ['dramatic_shadow', 0.78], ['golden_hour', 0.62]] },
        { intent: 1, loras: [['moody_atmosphere', 0.88], ['film_grain_warm', 0.54]] },
        { intent: 2, loras: [['dramatic_shadow', 0.93], ['cinematic_lighting_v2', 0.71]] },
      ],
    },
  },
  { id: 's-002', project_id: 'character-portraits', name: 'elf — archer sketch',
    model_name: 'illustriousXL_v01', use_negative: true, pinned: ['character_elf_archer'],
    source_image_path: null, vl_summary: null, messages: [], lastPrompt: null,
  },
  { id: 's-003', project_id: 'mood-tests', name: 'foggy street',
    model_name: 'flux_dev', use_negative: false, pinned: [],
    source_image_path: 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=900&q=80',
    vl_summary: 'Empty urban street at dawn. Cobblestones wet from recent rain. Thick fog limits visibility to ~30 meters. Cool blue-grey palette with a single warm streetlamp at mid-distance serving as focal point. Low-contrast, atmospheric, silent mood.',
    messages: [
      { role: 'user', content: 'Нравится туман и холодный тон, но добавь чуть больше тёплого источника вдалеке.' },
    ],
    lastPrompt: null,
  },
  { id: 's-004', project_id: 'mood-tests', name: 'chiaroscuro interior', model_name: 'juggernautXL_v10', use_negative: true, pinned: [],
    source_image_path: null, vl_summary: null, messages: [], lastPrompt: null,
  },
  { id: 's-005', project_id: 'scrapyard', name: 'test · film grain', model_name: 'juggernautXL_v10', use_negative: true, pinned: [],
    source_image_path: null, vl_summary: null, messages: [], lastPrompt: null,
  },
];

Object.assign(window, { FAMILIES, MODELS, LORAS, PROJECTS, INITIAL_SESSIONS });
